"""empty message

Revision ID: 7f889fc22912
Revises: bb7cc8beb93c
Create Date: 2022-02-10 22:04:28.188300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f889fc22912'
down_revision = 'bb7cc8beb93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('num_comments', sa.Integer(), nullable=True))
    op.alter_column('comment', 'comment_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('comment', 'deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('comment', 'dead',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.add_column('job', sa.Column('num_comments', sa.Integer(), nullable=True))
    op.alter_column('job', 'by',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.add_column('poll', sa.Column('num_comments', sa.Integer(), nullable=True))
    op.add_column('polloption', sa.Column('num_comments', sa.Integer(), nullable=True))
    op.add_column('story', sa.Column('num_comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'num_comments')
    op.drop_column('polloption', 'num_comments')
    op.drop_column('poll', 'num_comments')
    op.alter_column('job', 'by',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('job', 'num_comments')
    op.alter_column('comment', 'dead',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('comment', 'deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('comment', 'comment_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.drop_column('comment', 'num_comments')
    # ### end Alembic commands ###
